class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :email, null: false
      t.index :email, unique: true
      t.string :password, null: false
      # Leave off the unique constraint, have the candidate insert autogenerated usernames and add the constraint back.
      t.string :username, null: false
      t.index :username, unique: true
    end
  end
end
